import {renderWeeklyAnswers} from './weekly-checkin.js?v=23';
import {supabase} from './supabase.js?v=23';
import {todayBrussels,METRICS} from './tracking-model.js?v=23';
import {DEFAULT_ANALYSIS,calculateMacros,numberOrNull,energy,monday,addDays,weeklySummary,trainingSeries,effectivePrescription} from './analysis-model.js?v=23';
import {loadAnalysis,result,saveRevision} from './analysis-data.js?v=23';
import {n,fmt,field,select,button,section,table,chart} from './analysis-ui.js?v=23';
import {mountHistoryImport} from './history-import.js?v=23';
const macroFields=[['protein_g','Protéines (g)'],['carbs_g','Glucides (g)'],['fat_g','Lipides (g)'],['fiber_g','Fibres (g)']];
const metricLabel=k=>METRICS.find(m=>m[0]===k)?.[1]||({calories:'Calories',protein_g:'Protéines',carbs_g:'Glucides',fat_g:'Lipides',fiber_g:'Fibres',bp_systolic:'Pression systolique',bp_diastolic:'Pression diastolique'})[k]||k;
const macroLabel=m=>m?`${fmt(energy(m))} kcal · P ${fmt(m.protein_g)} / G ${fmt(m.carbs_g)} / L ${fmt(m.fat_g)} g`:'—';
export async function mountAnalysis(target,clientId,{coach=false,applyTargets=()=>{throw Error('Ouvre le constructeur alimentaire avant d’appliquer les macros.');}}={}){
 let alive=true,data,settings,conf;const destroy=()=>{alive=false;target.replaceChildren();};target.replaceChildren(n('p','Chargement des analyses…'));
 const msg=n('p','','inline-message');msg.setAttribute('role','status');
 const run=async(b,action)=>{b.disabled=true;try{await action();}catch(e){if(alive)msg.textContent=e.message;}finally{if(alive)b.disabled=false;}};
 try{data=await loadAnalysis(clientId);if(!alive)return {destroy};settings=data.settings;conf={...structuredClone(DEFAULT_ANALYSIS),...settings?.settings,sites:{...DEFAULT_ANALYSIS.sites,...settings?.settings?.sites},calculator:{...DEFAULT_ANALYSIS.calculator,...settings?.settings?.calculator}};
 target.replaceChildren(n('p',coach?'PILOTAGE CLIENT':'MA PROGRESSION','card-kicker'),n('h3',coach?'Calculs, roadmap et analyses':'Analyses et mensurations'),msg);
 const reload=button(target,'Actualiser les analyses',()=>run(reload,async()=>{data=await loadAnalysis(clientId);if(alive){renderReports();renderMeasurements();renderVersions();msg.textContent='Analyses actualisées.';}}));
 const saveConf=async()=>{settings=await saveRevision('coaching_analysis_settings',{client_id:clientId},'settings',conf,settings?.revision||0);if(alive)msg.textContent='Paramètres du client enregistrés.';};
 if(coach){
 const calc=section(target,'Calculateur de macros coach',true),form=n('form'),grid=n('div','','analysis-fields');form.append(grid);calc.append(form,n('p','Estimations issues des formules de ton classeur. Choisis ta méthode et ton ajustement avant d’appliquer les objectifs.','card-copy'));
 select(grid,'units','Unités',[['metric','kg / cm'],['imperial','lb / pouces']],conf.calculator.units);
 select(grid,'sex','Facteur de sexe de la formule',[['male','Masculin (+5)'],['female','Féminin (−161)']],conf.calculator.sex);
 for(const[k,label,min,max]of [['age','Âge (ans)',18,100],['weight','Poids (kg ou lb)',20,900],['height','Taille (cm ou pouces)',30,250],['body_fat','Masse grasse (%) — facultative',.1,74.9]])field(grid,k,label,{value:conf.calculator[k],min,max});
 select(grid,'activity','Activité',[[1.375,'Légère — 1,375'],[1.4625,'Légère à modérée — 1,4625'],[1.55,'Modérée — 1,55'],[1.6375,'Modérée à élevée — 1,6375'],[1.725,'Élevée — 1,725'],[1.9,'Très élevée — 1,9']],conf.calculator.activity);
 select(grid,'method','Méthode retenue',[['mifflin','Mifflin–St Jeor'],['katch','Katch–McArdle (masse grasse requise)'],['average','Moyenne des deux (masse grasse requise)']],conf.calculator.method);
 for(const[k,l,min,max]of [['adjustment_pct','Ajustement calorique (%)',-50,50],['protein_pct','Protéines (%)',0,100],['carbs_pct','Glucides (%)',0,100],['fat_pct','Lipides (%)',0,100]])field(grid,k,l,{value:conf.calculator[k],min,max});
 const output=n('div'),calcMsg=n('p','','inline-message');calcMsg.setAttribute('role','status');calc.append(calcMsg,output);let calculated=null;
 const values=()=>Object.fromEntries([...grid.querySelectorAll('input,select')].map(i=>[i.name,i.type==='number'?numberOrNull(i.value):i.value]));
 const compute=()=>{output.replaceChildren();try{calculated=calculateMacros(values());calcMsg.textContent='';table(output,['Estimation','kcal/jour'],[['Métabolisme Mifflin',fmt(calculated.mifflin)],['Métabolisme Katch',fmt(calculated.katch)],['Maintien Mifflin',fmt(calculated.estimates.mifflin)],['Maintien Katch',fmt(calculated.estimates.katch)],['Maintien moyen',fmt(calculated.estimates.average)],['Objectif après ajustement (4/4/9)',fmt(calculated.kcal)]],'Calculs énergétiques');output.append(n('p',macroLabel(calculated.macros)+` · Fibres ${fmt(calculated.macros.fiber_g)} g`));output.append(n('p',`Repères du classeur : 14 / 15 / 16 kcal/lb = ${calculated.poundsEstimates.map(fmt).join(' / ')} kcal ; protéines 2,3–3,1 g/kg = ${calculated.relativeProtein.map(fmt).join('–')} g ; lipides ${fmt(calculated.relativeFat)} g.`,'card-copy'));}catch(e){calculated=null;calcMsg.textContent=e.message;}};
 grid.addEventListener('input',compute);grid.addEventListener('change',compute);form.onsubmit=e=>{e.preventDefault();compute();};compute();
 const save=button(calc,'Enregistrer les paramètres du calculateur',()=>run(save,async()=>{compute();if(!calculated)throw Error(calcMsg.textContent);conf.calculator=values();await saveConf();}),true);
 const apply=button(calc,'Appliquer au plan alimentaire en cours',()=>{try{compute();if(!calculated)throw Error(calcMsg.textContent);applyTargets(calculated.macros);msg.textContent='Macros appliquées au brouillon alimentaire. Clique sur Enregistrer le programme pour les publier au client.';}catch(e){msg.textContent=e.message;}});
 const configuration=section(target,'Objectifs, mensurations et contexte client'),cg=n('div','','analysis-fields');configuration.append(cg);
 const sleep=field(cg,'sleep_goal','Objectif sommeil (h)',{value:conf.sleep_goal,max:24}),steps=field(cg,'steps_goal','Objectif pas / jour',{value:conf.steps_goal,max:100000,step:1});
 const contexts={};for(const[k,l]of [['priorities','Priorités du suivi'],['preferences','Préférences et allergies'],['supplements','Suppléments'],['health_context','Contexte signalé : médicaments, blessures'],['travel','Déplacements à venir']])contexts[k]=field(cg,k,l,{type:'textarea',value:conf[k]});
 configuration.append(n('p','Les neuf emplacements restent stables dans l’historique. Garde le même site anatomique lorsque tu renommes un libellé.','card-copy'));
 const sites={};for(const[k,s]of Object.entries(conf.sites)){const row=n('div','','analysis-site'),l=n('label',`Activer ${k.replace('site','site ')}`),check=n('input');check.type='checkbox';check.checked=s.enabled;l.append(check);row.append(l);const name=field(row,k,'Libellé du site (cm)',{type:'text',value:s.label});name.maxLength=80;sites[k]={check,name};configuration.append(row);}
 const sb=button(configuration,'Enregistrer les objectifs et options',()=>run(sb,async()=>{conf.sleep_goal=numberOrNull(sleep.value);conf.steps_goal=numberOrNull(steps.value);for(const[k,i]of Object.entries(contexts))conf[k]=i.value.trim();for(const[k,{check,name}]of Object.entries(sites)){if(!name.value.trim())throw Error('Chaque site doit avoir un libellé.');conf.sites[k]={label:name.value.trim(),enabled:check.checked};}await saveConf();renderMeasurements();}),true);
 }
 const roadmapEditor=coach?section(target,'Configurer une semaine de la roadmap'):null;
 if(coach){const form=n('form'),grid=n('div','','analysis-fields');form.append(grid);roadmapEditor.append(form);const week=field(grid,'week_start','Semaine du lundi',{type:'date',value:monday(todayBrussels())});week.required=true;
 const phase=field(grid,'phase','Phase',{type:'text'}),strategy=field(grid,'strategy','Stratégie nutrition',{type:'text'}),sleep=field(grid,'sleep_goal','Sommeil cible (h)',{max:24}),steps=field(grid,'steps_goal','Pas cibles / jour',{max:100000,step:1}),cardio=field(grid,'cardio','Cardio prescrit',{type:'textarea'});
 const macroInputs={};for(const[type,label]of [['training','Jour entraînement / haut'],['rest','Jour repos / bas']]){const block=n('div','','analysis-macro-block');block.append(n('h4',label));macroInputs[type]={};for(const[k,l]of macroFields)macroInputs[type][k]=field(block,type+'_'+k,l);const kcal=n('p');block.append(kcal);block.addEventListener('input',()=>kcal.textContent=`Calories automatiques : ${fmt(energy(Object.fromEntries(Object.entries(macroInputs[type]).map(([k,i])=>[k,numberOrNull(i.value)]))))} kcal`);grid.append(block);macroInputs[type].kcal=kcal;}
 const extra={};for(const[k,l]of [['expenditure','Précisions dépenses / activité'],['training_notes','Repères entraînement'],['events','Événements de la semaine'],['coach_notes','Notes de suivi']])extra[k]=field(grid,k,l,{type:'textarea'});
 const fill=()=>{if(week.value!==monday(week.value)){msg.textContent='Choisis le lundi de la semaine.';return;}const current=data.roadmap.find(r=>r.week_start===week.value)?.prescription;phase.value=current?.phase||'';strategy.value=current?.strategy||'';sleep.value=current?.sleep_goal??conf.sleep_goal??'';steps.value=current?.steps_goal??conf.steps_goal??'';cardio.value=current?.cardio||'';for(const[type,inputs]of Object.entries(macroInputs)){for(const[k]of macroFields)inputs[k].value=current?.[type]?.[k]??'';inputs.kcal.textContent=`Calories automatiques : ${fmt(energy(current?.[type]))} kcal`;}for(const[k,i]of Object.entries(extra))i.value=current?.[k]||'';};week.onchange=fill;fill();
 const draft=button(form,'Reprendre les macros du plan alimentaire',()=>{try{const plan=JSON.parse(applyTargets(null,true));for(const inputs of Object.values(macroInputs)){for(const[k]of macroFields)inputs[k].value=plan.targets?.[k]??'';inputs.kcal.textContent=`Calories automatiques : ${fmt(energy(plan.targets))} kcal`;}}catch(e){msg.textContent=e.message;}});
 const save=button(form,'Enregistrer cette prescription datée',()=>run(save,async()=>{if(!week.value||week.value!==monday(week.value))throw Error('La semaine doit commencer un lundi.');const p={phase:phase.value.trim(),strategy:strategy.value.trim(),sleep_goal:numberOrNull(sleep.value),steps_goal:numberOrNull(steps.value),cardio:cardio.value.trim()};for(const[type,inputs]of Object.entries(macroInputs)){p[type]=Object.fromEntries(macroFields.map(([k])=>[k,numberOrNull(inputs[k].value)]));const filled=macroFields.slice(0,3).filter(([k])=>p[type][k]!==null);if(filled.length&&filled.length!==3)throw Error('Renseigne les trois macros pour chaque type de jour, ou laisse-les toutes vides.');if(Object.values(p[type]).some(x=>x!==null&&(x<0||x>2000)))throw Error('Macro invalide.');}for(const[k,i]of Object.entries(extra))p[k]=i.value.trim();const old=data.roadmap.find(r=>r.week_start===week.value);const saved=await saveRevision('coaching_roadmap',{client_id:clientId,week_start:week.value},'prescription',p,old?.revision||0);if(!alive)return;data.roadmap=[...data.roadmap.filter(r=>r.week_start!==saved.week_start),saved];renderReports();msg.textContent='Prescription datée enregistrée. Elle s’applique dès ce lundi jusqu’à la suivante.';}),true);form.onsubmit=e=>{e.preventDefault();save.click();};
 }
 const reportArea=section(target,'Moyennes hebdomadaires et roadmap',true),graphs=section(target,'Graphiques du suivi'),training=section(target,'Progression entraînement'),measureArea=section(target,'Mensurations'),versions=coach?section(target,'Historique des programmes'):null;
 function renderReports(){reportArea.replaceChildren();graphs.replaceChildren();training.replaceChildren();const summaries=weeklySummary(data.entries,data.roadmap,data.dayTypes,[...data.roadmap.map(r=>r.week_start),...(data.checkIns||[]).filter(r=>r.week_start).map(r=>r.week_start)]);
 reportArea.append(n('p','Moyennes calculées uniquement sur les valeurs renseignées. Le nombre entre parenthèses indique les jours disponibles. Une semaine sans donnée reste vide. Les objectifs entraînement/repos nécessitent le type de journée renseigné.','card-copy'));
 if(!summaries.length)reportArea.append(n('p','Les premiers relevés alimenteront cette vue.','empty-state'));
 for(const w of [...summaries].reverse()){const box=n('details');box.append(n('summary',`${w.week} → ${addDays(w.week,6)} · ${w.days}/7 relevés · poids ${fmt(w.metrics.weight_kg?.value)} kg`));const p=effectivePrescription(data.roadmap,w.week);box.append(n('p',`${p?.phase||'Phase non définie'} · ${p?.strategy||'Stratégie non définie'} · variation ${fmt(w.weightDelta)} kg / ${fmt(w.weightPct)} %`));
 table(box,['Mesure','Moyenne réelle (jours)','Objectif moyen (jours)','Écart'],Object.entries(w.metrics).map(([k,m])=>{const goal=w.goals[k==='calories'?'kcal':k==='steps'?'steps_goal':k==='sleep_hours'?'sleep_goal':k];return [metricLabel(k)+(k==='fasting_glucose'?' (mg/dL, conversion mmol/L ×18,0182)':''),`${fmt(m.value)} (${m.count}/7)`,goal?`${fmt(goal.value)} (${goal.count}/7)`:'—',m.value!=null&&goal?.value!=null?fmt(m.value-goal.value):'—'];}),'Synthèse de la semaine');if(p){box.append(n('p','Entraînement : '+macroLabel(p.training)),n('p','Repos : '+macroLabel(p.rest)),n('p',`Type de journée renseigné : ${w.dayTypesCount}/7`));for(const[k,label]of [['cardio','Cardio'],['expenditure','Dépenses'],['training_notes','Entraînement'],['events','Événements'],['coach_notes','Notes']])if(p[k])box.append(n('p',label+' : '+p[k]));}const notes=w.rows.filter(r=>r.metrics.notes);if(notes.length){const context=n('details');context.append(n('summary','Notes et contexte de la semaine'));for(const r of notes)context.append(n('p',r.recorded_on+' : '+r.metrics.notes));box.append(context);}for(const checkIn of (data.checkIns||[]).filter(c=>c.kind==='weekly'&&c.week_start===w.week&&c.answers)){const form=n('details');form.append(n('summary','Questionnaire hebdomadaire — '+(checkIn.status==='reviewed'?'traité':'à traiter')));renderWeeklyAnswers(form,checkIn);box.append(form);}reportArea.append(box);}
 table(reportArea,['Semaine','Phase','Poids kg','Δ kg','Δ % poids','kcal entraînement','kcal repos','kcal réalisées','Pas cible','Pas réalisés'],summaries.map(w=>{const p=effectivePrescription(data.roadmap,w.week);return [w.week,p?.phase||'—',fmt(w.metrics.weight_kg?.value),fmt(w.weightDelta),fmt(w.weightPct),fmt(energy(p?.training)),fmt(energy(p?.rest)),fmt(w.metrics.calories?.value),fmt(p?.steps_goal??conf.steps_goal),fmt(w.metrics.steps?.value)];}),'Roadmap complète');
 const controls=n('div','','analysis-fields');graphs.append(controls);const period=select(controls,'period','Période',[[30,'30 jours'],[90,'90 jours'],[365,'1 an'],[730,'2 ans']],90),aggregation=select(controls,'aggregation','Affichage',[['daily','Journalier'],['weekly','Moyennes hebdomadaires']],'daily');const plot=n('div','','analysis-charts');graphs.append(plot);
 const draw=()=>{plot.replaceChildren();const since=addDays(todayBrussels(),-Number(period.value)),rows=data.entries.filter(r=>r.recorded_on>=since);const keys=[...new Set(['weight_kg','calories','sleep_hours','steps',...rows.flatMap(r=>Object.keys(r.metrics))])].filter(k=>!['notes','glucose_unit','menstruation'].includes(k));for(const k of keys){const calendar=Array.from({length:Number(period.value)+1},(_,i)=>{const date=addDays(since,i);return rows.find(r=>r.recorded_on===date)||{recorded_on:date,metrics:{}};});const points=aggregation.value==='weekly'?summaries.filter(w=>addDays(w.week,6)>=since).map(w=>({date:w.week,value:w.metrics[k]?.value??null})):calendar.map(r=>({date:r.recorded_on,value:k==='fasting_glucose'&&r.metrics[k]!=null?(r.metrics.glucose_unit==='mmol_l'?r.metrics[k]*18.0182:r.metrics.glucose_unit==='mg_dl'?r.metrics[k]:null):numberOrNull(r.metrics[k])}));chart(plot,metricLabel(k),points,k==='fasting_glucose'?'mg/dL':METRICS.find(m=>m[0]===k)?.[2]||(['protein_g','carbs_g','fat_g','fiber_g'].includes(k)?'g':k==='calories'?'kcal':''));}const menstrual=rows.filter(r=>r.metrics.menstruation);if(menstrual.length)table(plot,['Date','Menstruations'],menstrual.map(r=>[r.recorded_on,r.metrics.menstruation==='yes'?'Oui':'Non']),'Relevés menstruations');};period.onchange=draw;aggregation.onchange=draw;draw();
 const exerciseMap=new Map(data.sessions.flatMap(s=>(s.training_sets||[]).map(x=>[x.exercise_id,x.exercise_name])));if(!exerciseMap.size)training.append(n('p','Enregistre des séances pour afficher la progression.','empty-state'));else{const filters=n('div','','analysis-fields');training.append(filters);const ex=select(filters,'exercise','Exercice',[...exerciseMap]),metric=select(filters,'performance','Indicateur',[['load','Meilleure charge (kg)'],['reps','Meilleur nombre de répétitions'],['volume','Volume (kg × répétitions)']],'load'),area=n('div');training.append(n('p','Volume = somme des charges × répétitions enregistrées. Les répétitions d’échauffement ou non saisies ne sont pas ajoutées.','card-copy'),area);const draw=()=>{area.replaceChildren();chart(area,exerciseMap.get(ex.value),trainingSeries(data.sessions,ex.value,metric.value),metric.value==='load'?'kg':metric.value==='volume'?'kg × rép.':'rép.');};ex.onchange=draw;metric.onchange=draw;draw();}}
 function renderMeasurements(){measureArea.replaceChildren();const enabled=Object.entries(conf.sites).filter(([,s])=>s.enabled);if(!coach&&enabled.length){const form=n('form'),date=field(form,'date','Date des mensurations',{type:'date',value:todayBrussels()}),grid=n('div','','analysis-fields');date.max=todayBrussels();date.min=addDays(todayBrussels(),-730);date.required=true;form.append(grid);const inputs={};for(const[k,s]of enabled)inputs[k]=field(grid,k,s.label+' (cm)',{min:1,max:300});const fill=()=>{const old=data.measurements.find(r=>r.recorded_on===date.value);for(const[k,i]of Object.entries(inputs))i.value=old?.measurements[k]??'';};date.onchange=fill;fill();const save=button(form,'Enregistrer mes mensurations',()=>run(save,async()=>{const values=Object.fromEntries(Object.entries(inputs).filter(([,i])=>i.value!=='').map(([k,i])=>[k,Number(i.value)]));if(!Object.keys(values).length)throw Error('Renseigne au moins une mensuration.');const old=data.measurements.find(r=>r.recorded_on===date.value),saved=await saveRevision('client_measurements',{client_id:clientId,recorded_on:date.value},'measurements',{...Object.fromEntries(Object.entries(old?.measurements||{}).filter(([k])=>!conf.sites[k]?.enabled)),...values},old?.revision||0);if(alive){data.measurements=[...data.measurements.filter(r=>r.recorded_on!==saved.recorded_on),saved];renderMeasurements();msg.textContent='Mensurations partagées avec ton coach.';}}),true);form.onsubmit=e=>{e.preventDefault();save.click();};measureArea.append(form);}else if(!enabled.length)measureArea.append(n('p',coach?'Active les sites dans Objectifs, mensurations et contexte client.':'Ton coach n’a pas encore activé les mensurations.','empty-state'));
 const rows=[...data.measurements].sort((a,b)=>a.recorded_on.localeCompare(b.recorded_on));for(const[k,s]of Object.entries(conf.sites)){const points=rows.filter(r=>r.measurements[k]!=null).map(r=>({date:r.recorded_on,value:r.measurements[k]}));if(!points.length)continue;const first=points[0],last=points.at(-1);measureArea.append(n('p',`${s.label} : ${fmt(last.value)} cm · écart depuis ${first.date} : ${fmt(last.value-first.value)} cm`));chart(measureArea,s.label,points,'cm');}}
 function renderVersions(){if(!versions)return;versions.replaceChildren(n('p','Une version est conservée à chaque modification du programme. Les anciennes versions ne remplacent pas le programme actuel.','card-copy'));for(const v of [...data.versions].reverse()){const d=n('details');d.append(n('summary',new Date(v.saved_at).toLocaleString('fr-BE')));for(const[key,label]of [['nutrition_plan','Nutrition'],['training_plan','Entraînement']]){const pre=n('pre');try{pre.textContent=JSON.stringify(JSON.parse(v[key]),null,2);}catch{pre.textContent=v[key];}const block=n('details');block.append(n('summary',label),pre);d.append(block);}versions.append(d);}if(!data.versions.length)versions.append(n('p','Aucune version enregistrée.'));}
 renderReports();renderMeasurements();renderVersions();
 if(coach){const imports=section(target,'Importer un historique vérifié');mountHistoryImport(imports,clientId,{valid:()=>alive,onImported:async()=>{data=await loadAnalysis(clientId);if(alive){renderReports();renderMeasurements();renderVersions();}}});}
 if(!coach){const daily=section(target,'Type de journée : entraînement ou repos',true),form=n('form'),date=field(form,'date','Date',{type:'date',value:todayBrussels()});date.max=todayBrussels();date.min=addDays(todayBrussels(),-730);date.required=true;const type=select(form,'type','Type de journée',[['','Choisir'],['training','Entraînement'],['rest','Repos']]);const goal=n('p');form.append(goal);const fill=()=>{type.value=data.dayTypes.find(r=>r.recorded_on===date.value)?.day_type||'';const p=effectivePrescription(data.roadmap,date.value);goal.textContent=type.value?`Objectif de cette journée : ${macroLabel(p?.[type.value])}`:'Sélectionne le type de journée pour comparer tes apports.';};date.onchange=fill;type.onchange=()=>{const p=effectivePrescription(data.roadmap,date.value);goal.textContent='Objectif : '+macroLabel(p?.[type.value]);};fill();const save=button(form,'Enregistrer le type de journée',()=>run(save,async()=>{if(!type.value)throw Error('Choisis entraînement ou repos.');await result(supabase.from('client_day_types').upsert({client_id:clientId,recorded_on:date.value,day_type:type.value},{onConflict:'client_id,recorded_on'}));if(alive){data.dayTypes=[...data.dayTypes.filter(r=>r.recorded_on!==date.value),{recorded_on:date.value,day_type:type.value}];renderReports();msg.textContent='Type de journée enregistré.';}}),true);form.onsubmit=e=>{e.preventDefault();save.click();};daily.append(form);}
 return {destroy};
 }catch(e){if(alive)target.replaceChildren(n('p',e.message,'inline-message'));return {destroy};}
}
