export const n=(tag,text='',cls='')=>{const x=document.createElement(tag);x.textContent=text;x.className=cls;return x;};
export const fmt=v=>v==null?'—':new Intl.NumberFormat('fr-BE',{maximumFractionDigits:1}).format(v);
export function field(parent,name,label,{type='number',value='',min=0,max=2000,step=.1}={}){const l=n('label',label,'auth-field'),i=n(type==='textarea'?'textarea':'input');i.name=name;i.value=value??'';if(type!=='textarea')i.type=type;if(type==='number'){i.min=min;i.max=max;i.step=step;i.inputMode='decimal';}if(type==='textarea'){i.rows=3;i.maxLength=2000;}l.append(i);parent.append(l);return i;}
export function select(parent,name,label,options,value){const l=n('label',label,'auth-field'),s=n('select');s.name=name;s.setAttribute('aria-label',label);for(const[v,t]of options)s.append(new Option(t,v));if(value!=null)s.value=value;l.append(s);parent.append(l);return s;}
export function button(parent,label,action,primary=false){const b=n('button',label,primary?'auth-primary dashboard-submit':'auth-secondary');b.type='button';if(action)b.onclick=action;parent.append(b);return b;}
export function section(parent,title,open=false){const d=n('details','','analysis-section');d.open=open;d.append(n('summary',title));const content=n('div','','analysis-content');d.append(content);parent.append(d);return content;}
export function table(parent,headers,rows,caption){const wrap=n('div','','analysis-table'),t=n('table');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',caption);t.append(n('caption',caption));const head=n('thead'),tr=n('tr');for(const h of headers){const th=n('th',h);th.scope='col';tr.append(th);}head.append(tr);t.append(head);const body=n('tbody');for(const row of rows){const tr=n('tr');row.forEach((value,i)=>{const cell=n(i===0?'th':'td',String(value??'—'));if(i===0)cell.scope='row';tr.append(cell);});body.append(tr);}t.append(body);wrap.append(t);parent.append(wrap);}
export function chart(parent,label,points,unit=''){
 const card=n('figure','','analysis-chart');card.append(n('figcaption',label+(unit?' ('+unit+')':'')));const valid=points.filter(p=>p.value!=null&&Number.isFinite(p.value));if(!valid.length){card.append(n('p','Aucune donnée renseignée.','empty-state'));parent.append(card);return;}
 const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 600 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${label}, ${valid.length} valeurs. Minimum ${fmt(Math.min(...valid.map(p=>p.value)))}, maximum ${fmt(Math.max(...valid.map(p=>p.value)))} ${unit}. Détail accessible sous le graphique.`);
 const values=valid.map(p=>p.value),low=Math.min(...values),high=Math.max(...values),range=high-low||1;
 const dates=points.map(p=>p.date),first=new Date(dates[0]+'T12:00Z').getTime(),last=new Date(dates.at(-1)+'T12:00Z').getTime();const x=p=>48+(new Date(p.date+'T12:00Z').getTime()-first)/(last-first||1)*510,y=p=>180-(p.value-low)/range*145;
 const text=(x,y,t)=>{const el=document.createElementNS(NS,'text');el.setAttribute('x',x);el.setAttribute('y',y);el.textContent=t;svg.append(el);};text(2,30,fmt(high));text(2,180,fmt(low));text(48,210,dates[0]);text(455,210,dates.at(-1));
 let segment=[];const flush=()=>{if(segment.length>1){const line=document.createElementNS(NS,'polyline');line.setAttribute('points',segment.map(p=>`${x(p)},${y(p)}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#80D9CF');line.setAttribute('stroke-width','3');svg.append(line);}segment=[];};
 for(const p of points){if(p.value==null){flush();continue;}segment.push(p);}flush();for(const p of valid){const c=document.createElementNS(NS,'circle');c.setAttribute('cx',x(p));c.setAttribute('cy',y(p));c.setAttribute('r',4);c.setAttribute('fill','#80D9CF');const title=document.createElementNS(NS,'title');title.textContent=p.date+' : '+fmt(p.value)+' '+unit;c.append(title);svg.append(c);}card.append(svg);
 const details=n('details');details.append(n('summary','Voir les valeurs'));table(details,['Date','Valeur'],valid.map(p=>[p.date,fmt(p.value)]),label);card.append(details);parent.append(card);
}
