import {n,field,button,section,table,fmt} from './analysis-ui.js?v=25';
import {emptyAnnualPlan,normalizeAnnualPlan,annualWeeks,annualMonths} from './annual-roadmap-model.js?v=25';
import {todayBrussels} from './tracking-model.js?v=25';

// Persistence is injected so the host owns authentication, revision checks and RLS.
export async function mountAnnualRoadmap(target,clientId,{coach=false,load,save,today=todayBrussels()}={}){
 let alive=true,record=null,plan,saving=false;const destroy=()=>{alive=false;target.replaceChildren();};
 target.replaceChildren(n('p','Chargement du parcours annuel…'));
 try{record=await load(clientId);if(!alive)return {destroy};plan=record?.plan?normalizeAnnualPlan(record.plan):emptyAnnualPlan(today);}catch(e){if(alive)target.replaceChildren(n('p',e.message,'inline-message'));return {destroy};}
 target.replaceChildren();const message=n('p','','inline-message');message.setAttribute('role','status');target.append(message);
 const view=n('div'),editor=n('div');target.append(view,editor);
 function render(){view.replaceChildren(n('p','MON PARCOURS','card-kicker'),n('h3',plan.title));
 if(!record&&!coach){view.append(n('p','Ton coach prépare ton parcours annuel.','empty-state'));return;}
 const weeks=annualWeeks(plan,today),current=weeks.find(w=>w.status==='current');view.append(n('p',`${plan.start_date} → ${weeks.at(-1).end} · 52 semaines`,'card-copy'));
 if(plan.goal)view.append(n('p',plan.goal));view.append(n('p',current?`Tu es en semaine ${current.number} sur 52. ${current.phase?.title||'Phase à préciser avec ton coach.'}`:today<plan.start_date?'Ton parcours commence prochainement.':'Ce parcours de 52 semaines est terminé.'));
 view.append(n('p','Les phases donnent une direction et peuvent évoluer avec ton coach. Les objectifs affichés sont des prescriptions, les résultats restent dans les bilans hebdomadaires.','card-copy'));
 const overview=n('div','','annual-months');view.append(overview);for(const month of annualMonths(plan,today)){const card=n('article','','analysis-macro-block');card.append(n('h4',`Mois ${month.number}`),n('p',`${month.start} → ${month.end}`,'card-copy'),n('p',month.phases.map(p=>p.title).join(' → ')||'À planifier'));if(month.weeks.some(w=>w.status==='current')){card.setAttribute('aria-current','date');card.append(n('p','Tu es ici'));}overview.append(card);}
 for(const p of plan.phases){const block=section(view,`${p.title} · semaines ${p.start_week}–${p.end_week}`,current?.phase?.id===p.id);for(const[key,label]of [['purpose','Pourquoi cette phase'],['strategy','Stratégie nutrition'],['milestones','Étapes et repères'],['training_focus','Entraînement'],['activity_focus','Activité'],['events','Événements'],['notes','Notes du coach']])if(p[key])block.append(n('p',`${label} : ${p[key]}`));
 const t=p.targets;for(const[k,label]of [['standard_calories','Standard'],['high_calories','Jour haut'],['low_calories','Jour bas']])if(t[k]!=null)block.append(n('p',`${label} : ${fmt(t[k])} kcal`));for(const[type,label]of [['training','Entraînement'],['rest','Repos']])if(t[type]){const v=t[type];const kcal=v.calories??(['protein_g','carbs_g','fat_g'].every(k=>v[k]!=null)?v.protein_g*4+v.carbs_g*4+v.fat_g*9:null);block.append(n('p',`${label} : ${fmt(kcal)} kcal · P ${fmt(v.protein_g)} / G ${fmt(v.carbs_g)} / L ${fmt(v.fat_g)} g · Fibres ${fmt(v.fiber_g)} g`));}if(t.steps_goal!=null)block.append(n('p',`Pas cibles / jour : ${fmt(t.steps_goal)}`));if(t.sleep_goal!=null)block.append(n('p',`Sommeil cible : ${fmt(t.sleep_goal)} h`));if(t.cardio)block.append(n('p',`Cardio prescrit : ${t.cardio}`));}
 const detail=section(view,'Les 52 semaines datées');table(detail,['Semaine','Début','Fin','Phase','Stratégie','Situation'],weeks.map(w=>[w.number,w.start,w.end,w.phase?.title||'À planifier',w.phase?.strategy||'—',w.status==='current'?'Tu es ici':w.status==='past'?'Période passée':'À venir']),'Parcours annuel prévisionnel');
 }
 function edit(){editor.replaceChildren();if(!coach)return;const area=section(editor,'Configurer le parcours annuel'),form=n('form'),grid=n('div','','analysis-fields');area.append(form);form.append(grid);
 const start=field(grid,'start_date','Date de début',{type:'date',value:plan.start_date}),title=field(grid,'title','Titre du parcours',{type:'text',value:plan.title}),goal=field(grid,'goal','Direction et objectif du parcours',{type:'textarea',value:plan.goal});start.required=true;
 const phases=n('div');form.append(phases);const draft=structuredClone(plan.phases);const inputs=[];
 const addPhase=p=>{const box=n('fieldset');box.append(n('legend',`Phase ${inputs.length+1}`));phases.append(box);const fields={};const basic=n('div','','analysis-fields');box.append(basic);for(const[key,label,type]of [['title','Nom de la phase','text'],['start_week','Première semaine','number'],['end_week','Dernière semaine','number']])fields[key]=field(basic,key,label,{type,value:p[key],min:1,max:52,step:1});
 const advanced=section(box,'Détails de la phase');for(const[key,label,type]of [['purpose','Pourquoi cette phase','textarea'],['milestones','Étapes et repères','textarea'],['strategy','Stratégie nutrition','text'],['training_focus','Priorité entraînement','textarea'],['activity_focus','Priorité activité','textarea'],['events','Événements prévus','textarea'],['notes','Notes visibles du client','textarea']])fields[key]=field(advanced,key,label,{type,value:p[key]});
 const targetFields={};for(const[k,l,max]of [['standard_calories','Calories standard',15000],['high_calories','Calories jour haut',15000],['low_calories','Calories jour bas',15000],['steps_goal','Pas / jour',100000],['sleep_goal','Sommeil (h)',24]])targetFields[k]=field(advanced,k,l+' — facultatif',{value:p.targets?.[k],max});targetFields.cardio=field(advanced,'cardio','Cardio prescrit — facultatif',{type:'textarea',value:p.targets?.cardio});
 if(p.targets?.training||p.targets?.rest){const legacy=section(advanced,'Objectifs entraînement / repos existants — facultatifs');for(const[type,label]of [['training','Entraînement'],['rest','Repos']])if(p.targets?.[type]){legacy.append(n('h4',label));targetFields[type]={};for(const[k,l,max]of [['calories','Calories (kcal)',15000],['protein_g','Protéines (g)',1000],['carbs_g','Glucides (g)',2000],['fat_g','Lipides (g)',1000],['fiber_g','Fibres (g)',200]])targetFields[type][k]=field(legacy,type+'_'+k,l,{value:p.targets?.[type]?.[k],max});}}
 const item={p,fields,targetFields,removed:false};inputs.push(item);button(box,'Retirer cette phase',()=>{item.removed=true;box.remove();});};draft.forEach(addPhase);
 button(form,'Ajouter une phase',()=>{const active=inputs.filter(i=>!i.removed);if(active.length>=52){message.textContent='52 phases maximum.';return;}const next=Math.min(52,Math.max(0,...active.map(i=>Number(i.fields.end_week.value)||0))+1);addPhase({id:crypto.randomUUID(),start_week:next,end_week:next,title:'',targets:{}});});
 const submit=button(form,'Enregistrer le parcours annuel',async()=>{if(saving)return;saving=true;submit.disabled=true;try{const candidate=normalizeAnnualPlan({start_date:start.value,title:title.value,goal:goal.value,phases:inputs.filter(i=>!i.removed).map(({p,fields,targetFields})=>({...p,...Object.fromEntries(Object.entries(fields).map(([k,i])=>[k,i.value])),targets:{...p.targets,...Object.fromEntries(Object.entries(targetFields).map(([key,value])=>[key,['training','rest'].includes(key)?Object.fromEntries(Object.entries(value).map(([k,i])=>[k,i.value])):value.value]))}}))});const saved=await save(clientId,candidate,record?.revision||0);if(!alive)return;record=saved;plan=normalizeAnnualPlan(saved.plan);render();edit();message.textContent='Parcours annuel partagé avec le client.';}catch(e){if(alive)message.textContent=e.message;}finally{saving=false;if(alive)submit.disabled=false;}},true);form.onsubmit=e=>{e.preventDefault();submit.click();};
 }
 render();edit();return {destroy};
}
