import {supabase} from './supabase.js?v=25';
import {METRICS,validateMetrics,todayBrussels} from './tracking-model.js?v=25';
import {QUESTIONS,validateAnswers} from './coaching-model.js?v=25';
import {monday,addDays} from './analysis-model.js?v=25';
import {n,select,button,table} from './analysis-ui.js?v=25';
import {result} from './analysis-data.js?v=25';
export function parseCSV(text){
 const first=text.split(/\r?\n/,1)[0],separator=first.split(';').length>first.split(',').length?';':',';let rows=[],row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===separator&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Guillemets CSV non fermés.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)throw Error('Fichier vide.');rows[0][0]=rows[0][0].replace(/^\uFEFF/,'');if(rows.length>731)throw Error('Maximum 730 lignes par import.');return rows;
}
function dateValue(raw){const value=raw.trim();if(/^\d{4}-\d{2}-\d{2}T/.test(value)){const iso=value.slice(0,10);if(new Date(iso+'T12:00Z').toISOString().slice(0,10)===iso)return iso;}if(/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T12:00Z').toISOString().slice(0,10)===value)return value;const match=value.match(/^(\d{1,2})[/.](\d{1,2})[/.](\d{4})(?:\s.*)?$/);if(match){const date=`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`;if(new Date(date+'T12:00Z').toISOString().slice(0,10)===date)return date;}throw Error('Date invalide : '+value);}
export function mountHistoryImport(target,clientId,{onImported=()=>{},valid=()=>true}={}){
 target.append(n('p','Exporte l’onglet Tracking Sheet ou les réponses Google Forms en CSV. Choisis les colonnes, contrôle l’aperçu et confirme le client avant l’import. Les dates déjà présentes sont ignorées. Aucun ancien fichier n’est importé automatiquement.','card-copy'));
 const type=select(target,'kind','Historique à importer',[['daily','Suivi journalier'],['weekly','Questionnaire hebdomadaire']]),label=n('label','Fichier CSV','auth-field'),file=n('input');file.type='file';file.accept='.csv,text/csv';label.append(file);target.append(label);const header=select(target,'header','Ligne des titres des colonnes',[['0','Première ligne']],'0');const mapping=n('div','','analysis-fields'),preview=n('div'),status=n('p','','inline-message');status.setAttribute('role','status');target.append(mapping,preview,status);let raw=null,prepared=[],generation=0;
 const acknowledgment=n('label','Je confirme que ce fichier concerne le client ouvert dans cette fiche.','tracking-option'),check=n('input');check.type='checkbox';acknowledgment.prepend(check);target.append(acknowledgment);const importButton=button(target,'Importer les lignes vérifiées',async()=>{if(!check.checked||!prepared.length||!valid())return;importButton.disabled=true;file.disabled=type.disabled=header.disabled=check.disabled=true;let done=0;try{for(const row of prepared){if(!valid())throw Error('Import interrompu à la fermeture de la fiche.');await result(supabase.rpc(type.value==='daily'?'aa_import_daily':'aa_import_weekly',type.value==='daily'?{target_client:clientId,day:row.date,values_json:row.values}:{target_client:clientId,submitted_on:row.date,response_answers:row.values}));done++;status.textContent=`${done}/${prepared.length} lignes traitées.`;}await onImported();status.textContent=`${done} lignes traitées. Les doublons existants ont été conservés.`;}catch(e){if(valid())status.textContent=`${done} lignes traitées avant l’arrêt : ${e.message}. Les lignes restantes peuvent être réimportées.`;}finally{if(valid()){file.disabled=type.disabled=header.disabled=check.disabled=false;importButton.disabled=false;}}},true);importButton.disabled=true;
 const remap=()=>{prepared=[];check.checked=false;importButton.disabled=true;preview.replaceChildren();mapping.replaceChildren();if(!raw)return;const headerIndex=Number(header.value)||0,headers=raw[headerIndex],options=[['','Ignorer / non renseigné'],...headers.map((h,i)=>[String(i),`${i+1}. ${h||'Sans titre'}`])],selectors={};selectors.date=select(mapping,'date','Colonne date',options,headers.findIndex(h=>/^(date|recorded_on|horodateur)$/i.test(h.trim()))>=0?String(headers.findIndex(h=>/^(date|recorded_on|horodateur)$/i.test(h.trim()))):'');
 const fields=type.value==='daily'?[...METRICS.filter(m=>m[0]!=='blood_pressure').map(m=>[m[0],m[1]]),['protein_g','Protéines'],['carbs_g','Glucides'],['fat_g','Lipides'],['fiber_g','Fibres'],['bp_systolic','Pression systolique'],['bp_diastolic','Pression diastolique'],['glucose_unit','Unité glycémie (mg_dl ou mmol_l)']]:QUESTIONS.map(q=>[q.id,q.label]);for(const[k,label]of fields)selectors[k]=select(mapping,k,label,options,headers.includes(k)?String(headers.indexOf(k)):'');
 const review=button(preview,'Préparer et vérifier l’aperçu',()=>{prepared=[];importButton.disabled=true;const errors=[],seen=new Set();const display=n('div');if(selectors.date.value===''){status.textContent='Associe une colonne date.';return;}
 raw.slice(headerIndex+1).forEach((row,index)=>{try{if(!Object.entries(selectors).some(([k,s])=>k!=='date'&&s.value!==''&&(row[Number(s.value)]||'').trim()))return;const date=dateValue(row[Number(selectors.date.value)]||'');if(date>todayBrussels()||date<addDays(todayBrussels(),-730))throw Error('Date hors des deux dernières années.');const key=type.value==='weekly'?monday(date):date;if(seen.has(key))throw Error('Date ou semaine répétée dans le fichier.');seen.add(key);const values={};for(const[k,s]of Object.entries(selectors)){if(k==='date'||s.value==='')continue;let value=(row[Number(s.value)]||'').trim();if(!value)continue;if(k==='glucose_unit')value=value.toLowerCase().replace('/','_');if(k==='menstruation')value=({'oui':'yes','non':'no','yes':'yes','no':'no'})[value.toLowerCase()]||value;const numeric=type.value==='daily'?!['notes','glucose_unit','menstruation'].includes(k):QUESTIONS.find(q=>q.id===k)?.type==='scale';values[k]=numeric?Number(value.replace(',','.')):value;}
 if(type.value==='daily'){const settings={enabled_metrics:METRICS.map(m=>m[0]),macro_tracking:true};validateMetrics(values,settings);}else{const errors=validateAnswers(values);if(errors.length)throw Error('Réponses manquantes ou invalides : '+errors.map(e=>e.id).join(', '));}prepared.push({date,values});}catch(e){errors.push(`Ligne ${index+headerIndex+2} : ${e.message}`);}});
 const old=preview.querySelector('[data-preview]');old?.remove();display.dataset.preview='true';table(display,['Date','Valeurs'],prepared.map(r=>[r.date,Object.entries(r.values).map(([k,v])=>k+' : '+v).join(' · ')]),'Aperçu complet avant import');preview.append(display);status.textContent=errors.length?errors.join('\n'):`${prepared.length} lignes valides. Vérifie chaque ligne et confirme le client.`;if(errors.length)prepared=[];importButton.disabled=!prepared.length||!check.checked;});
 };type.onchange=header.onchange=remap;file.onchange=async()=>{const rev=++generation;raw=null;prepared=[];importButton.disabled=true;try{if(file.files[0].size>2*1024*1024)throw Error('Fichier CSV trop volumineux (2 Mo maximum).');raw=parseCSV(await file.files[0].text());header.replaceChildren(...raw.slice(0,40).map((row,i)=>new Option(`${i+1}. ${row.filter(Boolean).join(' / ').slice(0,120)}`,String(i))));const found=raw.findIndex(row=>row.some(h=>/^(date|recorded_on|horodateur)$/i.test(h.trim())));header.value=String(found>=0&&found<40?found:0);if(rev!==generation||!valid())return;status.textContent=`${raw.length-1} lignes détectées. Associe les colonnes et vérifie l’aperçu.`;remap();}catch(e){if(valid())status.textContent=e.message;}};check.onchange=()=>importButton.disabled=!check.checked||!prepared.length;
}
