import {supabase} from './supabase.js?v=23';
import {todayBrussels} from './tracking-model.js?v=23';
const bucket='aa-progress-photos';const poses=[['front','Face'],['side','Profil'],['back','Dos']];
const n=(tag,text,cls)=>{const x=document.createElement(tag);if(text)x.textContent=text;if(cls)x.className=cls;return x;};
async function result(p){const {data,error}=await p;if(error)throw Error(error.message);return data;}
export async function preparePhoto(file){
 if(!file||file.size>20*1024*1024||!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type))throw Error('Choisis une image JPEG, PNG ou WebP de moins de 20 Mo.');
 const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,2048/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));if(!blob||blob.size>3*1024*1024)throw Error('Image trop volumineuse après réduction.');return blob;}catch(e){throw Error(e.message.includes('volumineuse')?e.message:'Image illisible. Exporte-la en JPEG si elle est au format HEIC.');}finally{URL.revokeObjectURL(url);}
}
export async function mountPhotos(target,clientId,{coach=false,enabled=true}={}){
 let alive=true;const gallery=n('div'),comparison=n('div'),msg=n('p',null,'inline-message');msg.setAttribute('role','status');target.replaceChildren(n('h3','Photos de progression'),n('p','Photos privées partagées uniquement avec ton coach. Face, profil et dos : trois poses minimum.','card-copy'));
 const show=async()=>{try{const sets=await result(supabase.from('progress_photo_sets').select('*').eq('client_id',clientId).order('photographed_on',{ascending:false}).limit(24));if(!alive)return;mountComparison(sets||[]);gallery.replaceChildren();if(!sets?.length)gallery.append(n('p','Aucune série de photos enregistrée.','empty-state'));for(const set of sets||[]){const card=n('article',null,'progress-entry');card.append(n('strong',set.photographed_on));if(set.notes)card.append(n('p',set.notes));const grid=n('div',null,'photo-grid');card.append(grid);gallery.append(card);const urls=await result(supabase.storage.from(bucket).createSignedUrls(set.paths,600));if(!alive)return;for(let i=0;i<set.paths.length;i++){const figure=n('figure');figure.append(n('figcaption',poses[i]?.[1]||`Photo supplémentaire ${i-2}`));const data=urls.find(u=>u.path===set.paths[i]);if(data?.signedUrl){const image=n('img');image.src=data.signedUrl;image.alt=`${poses[i]?.[1]||'Pose supplémentaire'} — ${set.photographed_on}`;image.loading='lazy';image.referrerPolicy='no-referrer';figure.append(image);}else figure.append(n('p','Photo indisponible. Recharge la galerie.'));grid.append(figure);}}}catch(e){if(alive)msg.textContent=e.message;}};
 if(!coach&&enabled){const form=n('form'),dateLabel=n('label','Date des photos','auth-field'),date=n('input');date.type='date';date.required=true;date.value=todayBrussels();date.max=todayBrussels();dateLabel.append(date);form.append(dateLabel);const files=[];for(const [pose,label]of poses){const l=n('label',label+' (obligatoire)','auth-field'),input=n('input');input.type='file';input.name=pose;input.accept='image/jpeg,image/png,image/webp,image/heic,image/heif';input.required=true;l.append(input);form.append(l);files.push(input);}const moreLabel=n('label','Photos supplémentaires (jusqu’à 3)','auth-field'),more=n('input');more.type='file';more.multiple=true;more.accept=files[0].accept;moreLabel.append(more);form.append(moreLabel);const notesLabel=n('label','Note (facultative)','auth-field'),notes=n('textarea');notes.maxLength=1000;notesLabel.append(notes);form.append(notesLabel);const b=n('button','Envoyer mes photos','auth-primary dashboard-submit');b.type='submit';form.append(b);form.onsubmit=async e=>{e.preventDefault();const selected=[...files.map(i=>i.files[0]),...more.files];if(selected.some(f=>!f)||more.files.length>3){msg.textContent='Ajoute face, profil et dos, puis au maximum trois photos supplémentaires.';return;}const capturedDate=date.value,capturedNotes=notes.value.trim(),extraCount=more.files.length;for(const input of form.elements)input.disabled=true;const paths=[];try{msg.textContent='Préparation des photos…';const blobs=await Promise.all(selected.map(preparePhoto));if(!alive)return;const setId=crypto.randomUUID();for(let i=0;i<blobs.length;i++){if(!alive)throw Error('Envoi interrompu.');const path=`${clientId}/${setId}/${poses[i]?.[0]||'extra_'+(i-2)}.jpg`;msg.textContent=`Envoi de la photo ${i+1}/${blobs.length}…`;await result(supabase.storage.from(bucket).upload(path,blobs[i],{contentType:'image/jpeg',upsert:false}));paths.push(path);}await result(supabase.rpc('aa_commit_photos',{set_id:setId,day:capturedDate,extra_count:extraCount,photo_notes:capturedNotes}));if(!alive)return;form.reset();date.value=todayBrussels();msg.textContent='Les trois poses ont été enregistrées et partagées avec ton coach.';await show();}catch(e){if(paths.length)await supabase.storage.from(bucket).remove(paths);if(alive)msg.textContent=e.message;}finally{if(alive)for(const input of form.elements)input.disabled=false;}};target.append(form);}
 else if(!coach)target.append(n('p','Ton coach a désactivé l’ajout de photos. Ton historique reste disponible.','card-copy'));
 function mountComparison(sets){
 comparison.replaceChildren(n('h4','Comparaison avant / après — même pose'));
 if(sets.length<2){comparison.append(n('p','Ajoute deux séries datées pour comparer ta progression.','empty-state'));return;}
 const controls=n('div',null,'analysis-fields'),left=n('select'),right=n('select'),pose=n('select');
 const wrap=(label,input)=>{const l=n('label',label,'auth-field');l.append(input);controls.append(l);};
 sets.forEach((set,i)=>{left.append(new Option(set.photographed_on+' — série '+(i+1),set.id));right.append(new Option(set.photographed_on+' — série '+(i+1),set.id));});left.value=sets.at(-1).id;right.value=sets[0].id;poses.forEach(([key,label],i)=>pose.append(new Option(label,String(i))));
 wrap('Avant',left);wrap('Après',right);wrap('Pose à comparer',pose);const images=n('div',null,'photo-comparison');comparison.append(controls,images);let revision=0;
 const draw=async()=>{const rev=++revision;images.replaceChildren(n('p','Chargement des photos privées…'));try{const selected=[sets.find(x=>x.id===left.value),sets.find(x=>x.id===right.value)],index=Number(pose.value),paths=selected.map(x=>x.paths[index]);const urls=await result(supabase.storage.from(bucket).createSignedUrls([...new Set(paths)],600));if(!alive||rev!==revision)return;images.replaceChildren();for(let i=0;i<2;i++){const figure=n('figure');figure.append(n('figcaption',`${i===0?'Avant':'Après'} · ${selected[i].photographed_on} · ${poses[index][1]}`));const url=urls.find(u=>u.path===paths[i])?.signedUrl;if(url){const img=n('img');img.src=url;img.alt=`${poses[index][1]} — ${selected[i].photographed_on}`;img.referrerPolicy='no-referrer';figure.append(img);}else figure.append(n('p','Photo indisponible. Actualise la galerie.'));images.append(figure);}}catch(e){if(alive&&rev===revision)images.replaceChildren(n('p',e.message));}};
 left.onchange=right.onchange=pose.onchange=draw;void draw();
 }
 const refresh=n('button' ,'Actualiser la galerie','auth-secondary');refresh.type='button';refresh.onclick=show;target.append(msg,refresh,comparison,n('h4','Timeline des photos — face / profil / dos'),gallery);await show();return {destroy(){alive=false;target.replaceChildren();}};
}
