const n=(tag,text='',cls='')=>{const x=document.createElement(tag);x.textContent=text;x.className=cls;return x;};
const hosts=new Map();let ready=false;
function tabWorkspace(host,prefix,definitions){
 const nav=n('nav','','workspace-nav');nav.setAttribute('aria-label',prefix==='coach'?'Fiche client':'Mon espace');nav.setAttribute('role','tablist');
 const panes=new Map(),buttons=new Map();for(const[key,label]of definitions){const pane=n('section','','workspace-pane');pane.id=prefix+'-view-'+key;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-label',label);pane.tabIndex=0;const button=n('button',label,'workspace-tab');button.type='button';button.id=prefix+'-tab-'+key;button.setAttribute('role','tab');button.setAttribute('aria-controls',pane.id);pane.setAttribute('aria-labelledby',button.id);nav.append(button);host.append(pane);panes.set(key,pane);buttons.set(key,button);}
 host.prepend(nav);let current=null;
 const select=(key,update=true)=>{if(!panes.has(key))return;current=key;for(const[k,p]of panes)p.hidden=k!==key;for(const[k,b]of buttons){b.setAttribute('aria-selected',String(k===key));b.tabIndex=k===key?0:-1;}if(update)history.replaceState(null,'','#'+prefix+'-view-'+key);};
 for(const[key,b]of buttons){b.onclick=()=>select(key);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=[...buttons.keys()],i=keys.indexOf(current),next=e.key==='Home'?keys[0]:e.key==='End'?keys.at(-1):keys[(i+(e.key==='ArrowRight'?1:-1)+keys.length)%keys.length];select(next);buttons.get(next).focus();};}
 select(definitions[0][0],false);const value={host,panes,buttons,select,get current(){return current;}};hosts.set(prefix,value);return value;
}
function move(panel,selector){const el=document.querySelector(selector);if(el)panel.append(el);return el;}
function slot(panel,id){const el=n('div','','workspace-slot');el.id=id;panel.append(el);return el;}
function subPrograms(form,prefix,nutrition,training){const nav=n('nav','','program-nav');nav.setAttribute('aria-label','Type de programme');nav.setAttribute('role','tablist');const areas=[['nutrition','Alimentation',nutrition],['training','Entraînement',training]];const select=key=>{for(const[k,,area]of areas)area.hidden=k!==key;for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-selected',String(b.dataset.program===key));};for(const[k,label,area]of areas){area.dataset.programPanel=k;const b=n('button',label,'workspace-tab');b.type='button';b.dataset.program=k;b.setAttribute('role','tab');b.onclick=()=>select(k);nav.append(b);}form.prepend(nav);select('nutrition');return select;}
let coachProgram,clientProgram;
export function setupWorkspaces(){if(ready)return;ready=true;
 const client=document.querySelector('#client-dashboard'),clientHost=n('div','','workspace');client.append(clientHost);client.querySelector('.dashboard-intro nav')?.remove();client.querySelector('.dashboard-intro>p:last-child').textContent='Tes actions du jour, ton programme et ton parcours en un seul endroit.';
 const c=tabWorkspace(clientHost,'client',[['today','Aujourd’hui'],['programmes','Programmes'],['bilan','Bilan'],['annual','Parcours annuel'],['progress','Progression']]);
 const clientMessage=slot(clientHost,'client-analysis-message');clientHost.querySelector('.workspace-nav').after(clientMessage);slot(c.panes.get('progress'),'client-refresh-analyses');
 move(c.panes.get('today'),'#client-daily-tracking');slot(c.panes.get('today'),'client-day-type');move(c.panes.get('bilan'),'.checkin-card');move(c.panes.get('bilan'),'.history-card');slot(c.panes.get('bilan'),'client-weekly-report');
 const prog=move(c.panes.get('programmes'),'.programme-card'),articles=prog.querySelectorAll('.programme-section');clientProgram=subPrograms(prog,'client',articles[0],articles[1]);slot(c.panes.get('annual'),'client-annual-roadmap');move(c.panes.get('progress'),'#client-progress-photos');for(const id of ['client-graphs','client-measurements','client-training-analysis'])slot(c.panes.get('progress'),id);
 const history=document.querySelector('#client-progress-history')?.closest('section');if(history){const d=n('details','','legacy-history');d.append(n('summary','Anciennes mesures'));d.append(history);c.panes.get('progress').append(d);}
 const analysis=move(clientHost,'#client-analysis');analysis.hidden=true;client.querySelectorAll('.dashboard-grid').forEach(x=>{if(!x.children.length)x.remove();});
 const detail=document.querySelector('#coach-client-detail'),host=n('div','','workspace');detail.append(host);const w=tabWorkspace(host,'coach',[['bilan','Bilan'],['programmes','Programmes'],['annual','Parcours annuel'],['progress','Progression'],['settings','Paramètres']]);
 const coachMessage=slot(host,'coach-analysis-message');host.querySelector('.workspace-nav').after(coachMessage);slot(w.panes.get('progress'),'coach-refresh-analyses');
 move(w.panes.get('bilan'),'#coach-history');slot(w.panes.get('bilan'),'coach-weekly-report');slot(w.panes.get('bilan'),'coach-weekly-targets');move(w.panes.get('settings'),'.checkin-schedule');move(w.panes.get('settings'),'#coach-daily-tracking');for(const id of ['coach-client-settings','coach-imports'])slot(w.panes.get('settings'),id);
 const form=document.querySelector('#coach-plan-form'),card=form.closest('.dashboard-card');card.querySelector('nav')?.remove();w.panes.get('programmes').append(card);const nutrition=n('div'),training=n('div');nutrition.id='coach-nutrition-pane';training.id='coach-training-pane';nutrition.append(document.querySelector('#nutrition-builder'));training.append(document.querySelector('#training-builder'));form.prepend(nutrition,training);slot(nutrition,'coach-calculator');coachProgram=subPrograms(form,'coach',nutrition,training);form.querySelector('#coach-plan-submit').textContent='Enregistrer les programmes';
 const saveBar=n('div','','program-save-bar');saveBar.append(document.querySelector('#coach-plan-message'),document.querySelector('#coach-plan-submit'));form.append(saveBar);
 slot(w.panes.get('annual'),'coach-annual-roadmap');move(w.panes.get('progress'),'#coach-progress-photos');move(w.panes.get('progress'),'#coach-training-history');for(const id of ['coach-graphs','coach-measurements','coach-training-analysis','coach-plan-versions'])slot(w.panes.get('progress'),id);const old=document.querySelector('#coach-progress-history');if(old){const d=n('details','','legacy-history');d.append(n('summary','Anciennes mesures'),old);w.panes.get('progress').append(d);}
 const a=move(host,'#coach-analysis');a.hidden=true;detail.querySelector('.coach-client-tools')?.remove();
 const routeHash=()=>{const id=location.hash.slice(1);if(!id)return;const el=document.getElementById(id);const pane=el?.closest('.workspace-pane');if(pane){const prefix=pane.id.split('-view-')[0],key=pane.id.split('-view-')[1];hosts.get(prefix)?.select(key,false);if(el.closest('#coach-nutrition-pane'))coachProgram('nutrition');if(el.closest('#coach-training-pane'))coachProgram('training');return;}if(id==='coach-analysis'){w.select('programmes',false);coachProgram('nutrition');}if(id==='training-builder'){w.select('programmes',false);coachProgram('training');}};
 window.addEventListener('hashchange',routeHash);routeHash();
}
export function selectWorkspace(role,key){hosts.get(role)?.select(key,false);}
export function routeAnalysis(role,sections){const mapping={message:role+'-analysis-message',refresh:role+'-refresh-analyses',calculator:'coach-calculator',settings:'coach-client-settings',reports:role+'-weekly-report',weeklyTargets:'coach-weekly-targets',graphs:role+'-graphs',training:role+'-training-analysis',measurements:role+'-measurements',versions:'coach-plan-versions',imports:'coach-imports',dayType:'client-day-type'};for(const[k,id]of Object.entries(mapping)){const target=document.getElementById(id);if(target&&sections[k])target.replaceChildren(sections[k].closest('details')||sections[k]);}}
