import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
let playwright;try{playwright=require('playwright');}catch{playwright=require('/Users/axelandre/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const {chromium}=playwright;
const root=path.resolve(new URL('..',import.meta.url).pathname);
const scripts=existsSync(path.join(root,'scripts'))?'/scripts':'',styles=existsSync(path.join(root,'styles'))?'/styles':'';
let server,browser,base;
before(async()=>{
 server=createServer(async(req,res)=>{try{
  if(req.url==='/harness'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<html><head><link rel="stylesheet" href="${styles}/tokens.css"><link rel="stylesheet" href="${styles}/app.css"></head><body><main style="max-width:900px;margin:auto;padding:20px"><form id="weekly"></form><div id="builder"></div><div id="client"></div><div id="history"></div><div id="nutrition"></div></main><script type="module">import * as model from '${scripts}/coaching-model.js';import * as weekly from '${scripts}/weekly-checkin.js';import * as training from '${scripts}/training.js';import * as nutrition from '${scripts}/nutrition-builder.js';window.modules={model,weekly,training,nutrition};window.ready=true;</script></body></html>`);return;}
  const rel=decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(root,'.'+rel);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}
  const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'text/html');res.end(data);
 }catch{res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true});
});
after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));});
async function page(){const p=await browser.newPage({viewport:{width:390,height:844}});await p.goto(base+'/harness');await p.waitForFunction(()=>window.ready);return p;}
test('weekly client can answer all 26 questions and sees validation before sending',async()=>{
 const p=await page();await p.evaluate(()=>{window.editor=modules.weekly.mountWeeklyCheckIn(document.querySelector('#weekly'),{email:'client@example.com',fullName:'Client test',checkinDay:1});});
 assert.equal(await p.locator('#weekly [name]').count(),26);
 assert.match(await p.locator('#weekly').innerText(),/au plus tard à minuit/);
 const error=await p.evaluate(()=>{try{editor.serialize();return '';}catch(e){return e.message;}});assert.match(error,/obligatoires/);
 await p.evaluate(()=>{for(const q of modules.model.QUESTIONS){const input=document.querySelector(`[name="${q.id}"]`);if(q.required && !['email','full_name'].includes(q.id))input.value=q.type==='scale'?'5':'Ma réponse de cette semaine';}});
 const answers=await p.evaluate(()=>editor.serialize());assert.equal(answers.stress,5);assert.equal(answers.email,'client@example.com');
 await p.evaluate(()=>modules.weekly.mountWeeklyCheckIn(document.querySelector('#weekly'),{email:'client@example.com',fullName:'Client test',checkinDay:1,checkIns:[{kind:'weekly',week_start:modules.model.weeklyWindow(1).weekStart,created_at:new Date().toISOString()}]}));
 assert.equal(await p.locator('#checkin-submit').count(),0);assert.match(await p.locator('#weekly').innerText(),/Envoyé le/);await p.close();
});
test('coach composes a program and client records actual kg and reps separately from the target',async()=>{
 const p=await page();await p.evaluate(async()=>window.builder=await modules.training.mountTrainingBuilder(document.querySelector('#builder')));
 await p.locator('.training-library summary').click();await p.getByRole('searchbox',{name:'Rechercher un exercice'}).fill('1-Arm DB Row');await p.locator('.exercise-result').first().click();
 await p.getByLabel('Charge cible (kg)',{exact:true}).fill('42.5');
 const plan=await p.evaluate(()=>JSON.parse(builder.serialize()));assert.equal(plan.days[0].exercises[0].targetLoadKg,42.5);assert.equal(plan.days[0].exercises[0].sets,3);
 await p.evaluate(plan=>{document.querySelector('#builder').replaceChildren();modules.training.renderClientTraining(document.querySelector('#client'),JSON.stringify(plan),{onSubmit:async(day,logs)=>window.savedLogs={day,logs}});},plan);
 await p.locator('.client-session summary').click();await p.getByRole('button',{name:'Enregistrer cette séance'}).click();assert.match(await p.locator('.workout-form .inline-message').innerText(),/au moins une série/);
 await p.locator('.workout-set input[type=checkbox]').first().check();await p.locator('.workout-set').first().getByLabel('Répétitions',{exact:true}).fill('9');await p.locator('.workout-set').first().getByLabel('Charge (kg)',{exact:true}).fill('40.2');assert.equal(await p.locator('.workout-set').first().getByLabel('Charge (kg)',{exact:true}).evaluate(input=>input.validity.stepMismatch),false);await p.getByRole('button',{name:'Enregistrer cette séance'}).click();
 await p.waitForFunction(()=>window.savedLogs);const result=await p.evaluate(()=>window.savedLogs);assert.equal(result.logs[0].load_kg,40.2);assert.equal(result.logs[0].reps,9);assert.equal(plan.days[0].exercises[0].targetLoadKg,42.5);
 assert.equal(await p.getByRole('button',{name:'Séance enregistrée',exact:true}).isDisabled(),true);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await p.screenshot({path:'/private/tmp/aa-training-mobile.png',fullPage:true});await p.close();
});
test('V4 nutrition uses the selected food to calculate and serialize the actual portion',async()=>{
 const p=await page();await p.evaluate(async()=>window.nutritionEditor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition')));
 await p.locator('.nutrition-meal').first().getByRole('searchbox').fill('Poulet poitrine chair maigre');await p.locator('.nutrition-search__result').first().waitFor();await p.locator('.nutrition-search__result').first().click();await p.locator('.nutrition-meal').first().getByLabel('Quantité (g)',{exact:true}).fill('150');await p.locator('.nutrition-meal').first().getByRole('button',{name:'Ajouter l’aliment'}).click();
 const plan=await p.evaluate(()=>JSON.parse(nutritionEditor.serialize()));const item=plan.meals[0].items[0];assert.equal(item.grams,150);
 assert.match(await p.locator('.nutrition-meal__totals').first().innerText(),new RegExp(`${Math.round((4*item.per100g.protein_g+4*item.per100g.carbs_g+9*item.per100g.fat_g)*1.5)} kcal`));
 assert.equal(Number(await p.locator('.nutrition-comparison__actual [data-metric=kcal]').getAttribute('data-value')),Number(((4*item.per100g.protein_g+4*item.per100g.carbs_g+9*item.per100g.fat_g)*1.5).toFixed(2)));
 await p.locator('.nutrition-item').first().getByRole('spinbutton').fill('250');assert.match(await p.locator('.nutrition-meal__totals').first().innerText(),new RegExp(`${Math.round((4*item.per100g.protein_g+4*item.per100g.carbs_g+9*item.per100g.fat_g)*2.5)} kcal`));await p.close();
});

function supabaseStub(role) {
 return `const user={id:'11111111-1111-4111-a111-111111111111',email:'fixture@example.invalid'};
 const client={id:'22222222-2222-4222-a222-222222222222',full_name:'Client de test',checkin_day:2};
 const records=[];let savedPlan=null;
 export const supabase={auth:{getSession:async()=>({data:{session:{user}}}),getUser:async()=>({data:{user}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({})},
 from(table){let many=false;const q={select(){return q},eq(){return q},in(){many=true;return q},order(){return q},limit(){return q},range(){return q},gte(){return q},upsert(value){savedPlan=value;window.savedPlan=value;return q},
 maybeSingle:async()=>({data:table==='profiles'?{id:user.id,role:'${role}',full_name:'Profil de test',checkin_day:2}:savedPlan,error:null}),single:async()=>({data:savedPlan,error:null}),
 then(resolve,reject){let data=table==='coach_clients'?[{client_id:client.id}]:table==='profiles'?(many?[client]:[]):table==='check_ins'?records:[];return Promise.resolve({data,error:null}).then(resolve,reject)}};return q},
 rpc:async(name,payload)=>{window.rpcCalls=window.rpcCalls||[];window.rpcCalls.push({name,payload});if(name==='aa_submit_weekly_check_in'){records.push({id:'weekly-fixture',kind:'weekly',body:'Questionnaire',answers:payload.response_answers,week_start:new Intl.DateTimeFormat('en-CA').format(new Date()),created_at:new Date().toISOString(),status:'pending'});}return {data:'fixture-result',error:null}},functions:{invoke:async()=>({data:{message:'Test'},error:null})}};`;
}
test('signed-in coach can load both editors, choose the check-in day and save a structured program',async()=>{
 const p=await browser.newPage({viewport:{width:1200,height:900},serviceWorkers:'block'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/supabase.js*',route=>route.fulfill({status:200,contentType:'application/javascript',body:supabaseStub('coach')}));await p.goto(base+'/index.html');
 await p.locator('.client-row').click();await p.locator('#training-builder .training-library').waitFor();assert.equal(await p.locator('#nutrition-builder .nutrition-meal').count(),6);
 assert.equal(await p.locator('#checkin-schedule-form select').inputValue(),'2');await p.locator('#checkin-schedule-form select').selectOption('3');await p.getByRole('button',{name:'Enregistrer le jour de check-in'}).click();
 await p.waitForFunction(()=>window.rpcCalls?.length);const rpc=await p.evaluate(()=>window.rpcCalls[0]);assert.equal(rpc.name,'aa_set_checkin_day');assert.equal(rpc.payload.weekday,3);
 await p.getByRole('link',{name:'Plan d’entraînement',exact:true}).click();assert.equal(await p.evaluate(()=>location.hash),'#training-builder');await p.locator('.training-library summary').click();await p.getByRole('searchbox',{name:'Rechercher un exercice'}).fill('1-Arm DB Row');await p.locator('.exercise-result').first().click();
 await p.getByRole('button',{name:'Enregistrer le programme',exact:true}).click();await p.waitForFunction(()=>window.savedPlan);const saved=await p.evaluate(()=>window.savedPlan);assert.equal(JSON.parse(saved.training_plan).schema,'aa-training-plan');assert.equal(JSON.parse(saved.nutrition_plan).schema,'aa-nutrition-plan');assert.deepEqual(errors,[]);await p.close();
});
test('signed-in client loads the complete weekly form in the existing dashboard',async()=>{
 const p=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/supabase.js*',route=>route.fulfill({status:200,contentType:'application/javascript',body:supabaseStub('client')}));await p.goto(base+'/index.html');await p.locator('#checkin-form [name=full_name]').waitFor();
 assert.equal(await p.locator('#checkin-form [name]').count(),26);assert.match(await p.locator('#checkin-form .weekly-status').innerText(),/Mardi/);assert.equal(await p.locator('#checkin-form [name=email]').inputValue(),'fixture@example.invalid');assert.deepEqual(errors,[]);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await p.screenshot({path:'/private/tmp/aa-checkin-mobile.png',fullPage:true});await p.close();
});

test('nutrition automatically calculates theoretical kcal and compares the live daily plan after edits',async()=>{
 const p=await page();const saved={schema:'aa-nutrition-plan',version:1,targets:{kcal:9999,protein_g:200,carbs_g:250,fat_g:70},meals:[{name:'Repas 1',items:[{foodId:'fixture',name:'Aliment de test',source:'AA_CUSTOM',grams:100,per100g:{kcal:999,protein_g:20,carbs_g:30,fat_g:10,fiber_g:2}}]},{name:'Repas 2',items:[{foodId:'fixture2',name:'Aliment 2',source:'AA_CUSTOM',grams:100,per100g:{kcal:999,protein_g:20,carbs_g:30,fat_g:10,fiber_g:2}}]}]};
 await p.evaluate(async saved=>window.nutritionEditor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition'),JSON.stringify(saved)),saved);
 const calories=p.getByLabel('Calories théoriques (kcal)',{exact:true});assert.equal(await calories.count(),1);assert.equal(await calories.isEditable(),false);assert.equal(await calories.inputValue(),'2430');
 const actual=p.locator('.nutrition-comparison__actual');assert.equal(await actual.locator('[data-metric=kcal]').getAttribute('data-value'),'580');
 await p.getByLabel('Protéines (g)',{exact:true}).fill('40');await p.getByLabel('Glucides (g)',{exact:true}).fill('60');await p.getByLabel('Lipides (g)',{exact:true}).fill('20');assert.equal(await calories.inputValue(),'580');
 assert.equal(await p.locator('.nutrition-comparison__delta [data-metric=kcal]').innerText(),'0');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await p.setViewportSize({width:1100,height:900});await p.locator('.nutrition-targets').scrollIntoViewIfNeeded();await p.screenshot({path:'/private/tmp/aa-macro-comparison.png',fullPage:false});
 await p.locator('.nutrition-item').first().getByRole('spinbutton').fill('200');assert.equal(await actual.locator('[data-metric=kcal]').getAttribute('data-value'),'870');
 await p.locator('.nutrition-item').first().getByRole('button',{name:'Retirer'}).click();assert.equal(await actual.locator('[data-metric=kcal]').getAttribute('data-value'),'290');
 assert.equal((await p.evaluate(()=>JSON.parse(nutritionEditor.serialize()))).targets.kcal,580);
 await p.close();
});
test('coach can choose an exercise from a list filtered by muscle and equipment',async()=>{
 const p=await page();await p.evaluate(async()=>window.builder=await modules.training.mountTrainingBuilder(document.querySelector('#builder')));await p.locator('.training-library summary').click();
 await p.getByRole('combobox',{name:'Filtrer par muscle'}).selectOption('dorsaux');await p.getByRole('combobox',{name:'Filtrer par matériel'}).selectOption('Dumbbell');
 assert.equal(await p.getByRole('combobox',{name:'Choisir un exercice'}).count(),1);await p.getByRole('combobox',{name:'Choisir un exercice'}).selectOption({label:'1-Arm DB Row'});
 const plan=await p.evaluate(()=>JSON.parse(builder.serialize()));assert.equal(plan.days[0].exercises.length,1);assert.equal(plan.days[0].exercises[0].name,'1-Arm DB Row');assert.equal(plan.days[0].exercises[0].muscle,'dorsaux');await p.close();
});

test('existing calorie-only targets are retained until macros change and empty goals remain null',async()=>{
 const p=await page();await p.evaluate(async()=>window.nutritionEditor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition'),JSON.stringify({schema:'aa-nutrition-plan',version:1,targets:{kcal:2000},meals:[]})));
 assert.equal((await p.evaluate(()=>JSON.parse(nutritionEditor.serialize()))).targets.kcal,2000);
 await p.getByLabel('Protéines (g)',{exact:true}).fill('100');assert.equal(await p.getByLabel('Calories théoriques (kcal)',{exact:true}).inputValue(),'400');
 await p.getByLabel('Protéines (g)',{exact:true}).fill('');assert.equal((await p.evaluate(()=>JSON.parse(nutritionEditor.serialize()))).targets.kcal,null);
 await p.getByLabel('Lipides (g)',{exact:true}).fill('-1');assert.match(await p.evaluate(()=>{try{nutritionEditor.serialize();return '';}catch(e){return e.message;}}),/Lipides/);
 await p.close();
});

test('comparison deltas agree with the displayed rounded macro amounts',async()=>{
 const p=await page();const plan={schema:'aa-nutrition-plan',version:1,targets:{protein_g:3.7,carbs_g:0,fat_g:0},meals:[{items:[{name:'Test',grams:100,per100g:{kcal:0,protein_g:3.75,carbs_g:0,fat_g:0}}]}]};
 await p.evaluate(async plan=>modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition'),JSON.stringify(plan)),plan);
 assert.equal(await p.locator('.nutrition-comparison__theory [data-metric=protein_g]').innerText(),'3,7');assert.equal(await p.locator('.nutrition-comparison__actual [data-metric=protein_g]').innerText(),'3,8');assert.equal(await p.locator('.nutrition-comparison__delta [data-metric=protein_g]').innerText(),'+0,1');await p.close();
});

function trackingStub(){return `
let settings={enabled_metrics:['weight_kg','steps','sleep_hours','stress','fasting_glucose','blood_pressure','menstruation','notes'],macro_tracking:true,photos_enabled:true,revision:1},rows=[],sets=[];
window.trackingCalls=[];window.uploadCalls=[];
export const supabase={from(table){let date=null;const q={select(){return q},eq(k,v){if(k==='recorded_on')date=v;return q},order(){return q},limit(){return q},maybeSingle:async()=>({data:table==='client_tracking_settings'?settings:rows.find(r=>r.recorded_on===date)||null,error:null}),then(resolve){return Promise.resolve({data:table==='daily_tracking_entries'?rows:sets,error:null}).then(resolve)}};return q},rpc:async(name,p)=>{window.trackingCalls.push({name,p});if(name==='aa_save_daily'){const m={...p.values_json,calories:p.values_json.protein_g*4+p.values_json.carbs_g*4+p.values_json.fat_g*9};const r={recorded_on:p.day,metrics:m,revision:1};rows.push(r);return {data:[r],error:null};}if(name==='aa_save_tracking_settings'){settings={enabled_metrics:p.options,macro_tracking:p.macros,photos_enabled:p.photos,revision:2};return {data:[settings],error:null};}sets.push({photographed_on:p.day,paths:['front','side','back'].map(k=>'fixture/'+p.set_id+'/'+k+'.jpg'),notes:p.photo_notes});return {data:sets[sets.length-1],error:null}},storage:{from(){return {upload:async(path,blob,options)=>{window.uploadCalls.push({path,size:blob.size,type:blob.type,options});return window.failUpload&&window.uploadCalls.length===2?{error:{message:'Échec simulé'}}:{data:{path},error:null};},remove:async(paths)=>{window.removedPaths=paths;return {data:[],error:null}},createSignedUrls:async(paths)=>({data:paths.map(path=>({path,signedUrl:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'})),error:null})}}}};`;}
async function trackingPage(){const p=await browser.newPage({viewport:{width:390,height:844}});await p.route('**/supabase.js*',r=>r.fulfill({status:200,contentType:'application/javascript',body:trackingStub()}));await p.goto(base+'/harness');await p.waitForFunction(()=>window.ready);return p;}
test('daily client enters tracking and Cronometer totals, calories calculate and date changes load empty values',async()=>{
 const p=await trackingPage();await p.evaluate(async scripts=>{const m=await import(scripts+'/tracking.js');window.tracker=await m.mountTracking(document.querySelector('#client'),'fixture');},scripts);
 await p.getByLabel('Poids (kg)',{exact:true}).fill('70.5');await p.getByLabel('Protéines (g)',{exact:true}).fill('150');await p.getByLabel('Glucides (g)',{exact:true}).fill('200');await p.getByLabel('Lipides (g)',{exact:true}).fill('60');assert.equal(await p.getByLabel('Calories consommées').inputValue(),'1940');assert.equal(await p.getByLabel('Calories consommées').isEditable(),false);await p.getByRole('button',{name:'Enregistrer mon suivi'}).click();await p.getByText('Suivi enregistré et partagé avec ton coach.').waitFor();const calls=await p.evaluate(()=>window.trackingCalls);assert.equal(calls[0].p.values_json.weight_kg,70.5);assert.equal(calls[0].p.values_json.steps,null);assert.ok(!('calories' in calls[0].p.values_json));assert.match(await p.locator('#client').innerText(),/Calories \(kcal\) : 1940/);
 await p.getByLabel('Date du suivi').fill('2026-10-01');await p.getByLabel('Date du suivi').dispatchEvent('change');await p.waitForFunction(()=>document.querySelector('[name=weight_kg]').value==='');assert.equal(await p.getByLabel('Calories consommées').inputValue(),'');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'/private/tmp/aa-daily-tracking.png',fullPage:true});await p.close();
});
test('coach selects each daily option including menstruation and can turn Cronometer off',async()=>{
 const p=await trackingPage();await p.evaluate(async scripts=>{const m=await import(scripts+'/tracking.js');await m.mountTracking(document.querySelector('#client'),'fixture',{coach:true});},scripts);await p.getByLabel('Menstruations',{exact:true}).uncheck();await p.getByLabel('Macros via Cronometer',{exact:true}).uncheck();await p.getByLabel('Récupération',{exact:true}).check();await p.getByRole('button',{name:'Enregistrer les options'}).click();await p.getByText('Options enregistrées.',{exact:false}).waitFor();const saved=await p.evaluate(()=>window.trackingCalls[0].p);assert.equal(saved.macros,false);assert.ok(saved.options.includes('recovery'));assert.ok(!saved.options.includes('menstruation'));await p.close();
});
const tinyPng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6E1cAAAAASUVORK5CYII=','base64');
test('progress photos require three poses and upload JPEG with no overwrite before committing the complete set',async()=>{
 const p=await trackingPage();await p.evaluate(async scripts=>{const m=await import(scripts+'/progress-photos.js');await m.mountPhotos(document.querySelector('#client'),'fixture');},scripts);await p.getByRole('button',{name:'Envoyer mes photos'}).click();assert.equal(await p.evaluate(()=>window.uploadCalls.length),0);for(const label of ['Face','Profil','Dos'])await p.getByLabel(label+' (obligatoire)',{exact:true}).setInputFiles({name:label+'.png',mimeType:'image/png',buffer:tinyPng});await p.getByRole('button',{name:'Envoyer mes photos'}).click();await p.getByText('Les trois poses ont été enregistrées',{exact:false}).waitFor();const uploads=await p.evaluate(()=>window.uploadCalls);assert.equal(uploads.length,3);assert.ok(uploads.every(u=>u.type==='image/jpeg'&&u.options.upsert===false));assert.match(uploads[0].path,/front\.jpg$/);assert.equal(await p.locator('.photo-grid img').count(),3);await p.close();
});
test('failed photo upload cleans incomplete files and never reports a saved series',async()=>{
 const p=await trackingPage();await p.evaluate(async scripts=>{window.failUpload=true;const m=await import(scripts+'/progress-photos.js');await m.mountPhotos(document.querySelector('#client'),'fixture');},scripts);for(const label of ['Face','Profil','Dos'])await p.getByLabel(label+' (obligatoire)',{exact:true}).setInputFiles({name:label+'.png',mimeType:'image/png',buffer:tinyPng});await p.getByRole('button',{name:'Envoyer mes photos'}).click();await p.getByText('Échec simulé',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.trackingCalls.length),0);assert.equal(await p.evaluate(()=>window.removedPaths.length),1);assert.equal(await p.getByRole('button',{name:'Envoyer mes photos'}).isDisabled(),false);await p.close();
});

test('food search can use only the personal AA database, Ciqual, USDA or all sources across meals',async()=>{
 const p=await page();await p.evaluate(async()=>window.editor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition')));
 const filter=p.getByLabel('Base alimentaire pour la recherche',{exact:true});assert.equal(await filter.locator('option[value=AA_CUSTOM]').textContent(),'Ma base personnelle AA');assert.equal(await filter.locator('option[value=all]').textContent(),'Toutes les bases');await filter.selectOption('AA_CUSTOM');const meal=p.locator('.nutrition-meal').first();await meal.getByRole('searchbox').fill('riz');await meal.locator('.nutrition-search__result').first().waitFor();assert.ok((await meal.locator('.nutrition-search__source').allTextContents()).every(t=>t.includes('AA CUSTOM')));
 await meal.locator('.nutrition-search__result').first().click();assert.ok(!(await meal.locator('.nutrition-search__selected').innerText()).includes('Aucun'));await filter.selectOption('CIQUAL_2025');await meal.locator('.nutrition-search__result').first().waitFor();assert.ok((await meal.locator('.nutrition-search__source').allTextContents()).every(t=>t.includes('CIQUAL 2025')));assert.equal(await meal.locator('.nutrition-search__selected').innerText(),'Aucun aliment sélectionné');
 await filter.selectOption('usda');await meal.getByRole('searchbox').fill('rice');await meal.locator('.nutrition-search__result').first().waitFor();assert.ok((await meal.locator('.nutrition-search__source').allTextContents()).every(t=>t.includes('USDA')));
 await filter.selectOption('AA_CUSTOM');await p.evaluate(async()=>window.editor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition')));assert.equal(await p.getByLabel('Base alimentaire pour la recherche',{exact:true}).inputValue(),'AA_CUSTOM');await p.close();
});

test('workout shows exercise preview, video and each set from the latest matching session, then fresh results after restart',async()=>{
 const p=await page();const plan={schema:'aa-training-plan',version:1,name:'Programme test',mode:'weekly',days:[{id:'day-a',name:'Séance A',exercises:[{id:'row-a',exerciseId:'ex-a',name:'Exercice test',image:'https://drive.google.com/file/d/example_test_gif/view',video:'https://youtu.be/example',sets:2,repsMin:8,repsMax:12,restSeconds:90}]}]};
 const history=[{plan_day_id:'day-other',performed_on:'2026-10-05',created_at:'2026-10-05T12:00:00Z',training_sets:[{exercise_item_id:'row-a',exercise_id:'ex-a',set_index:1,reps:99,load_kg:999}]},{plan_day_id:'day-a',performed_on:'2026-10-04',created_at:'2026-10-04T12:00:00Z',training_sets:[{exercise_item_id:'row-a',exercise_id:'ex-a',set_index:1,reps:10,load_kg:40},{exercise_item_id:'row-a',exercise_id:'ex-a',set_index:2,reps:9,load_kg:40}]},{plan_day_id:'day-a',performed_on:'2026-10-01',created_at:'2026-10-01T12:00:00Z',training_sets:[{exercise_item_id:'row-a',exercise_id:'ex-a',set_index:1,reps:8,load_kg:35}]}];
 await p.route('https://drive.google.com/**',r=>r.fulfill({status:200,contentType:'text/html',body:'<p>Animation fictive</p>'}));
 await p.evaluate(({plan,history})=>modules.training.renderClientTraining(document.querySelector('#client'),JSON.stringify(plan),{history,onSubmit:async(dayId,logs,notes)=>{window.performanceSaved={dayId,logs,notes};}}),{plan,history});await p.locator('.client-session summary').click();assert.equal(await p.locator('iframe.exercise-preview').getAttribute('src'),'https://drive.google.com/file/d/example_test_gif/preview');assert.equal(await p.getByRole('link',{name:'Voir la vidéo',exact:true}).getAttribute('href'),'https://youtu.be/example');assert.match(await p.locator('.workout-set').first().innerText(),/10 répétitions · 40 kg/);assert.match(await p.locator('.workout-set').nth(1).innerText(),/9 répétitions · 40 kg/);assert.ok(!(await p.locator('#client').innerText()).includes('999 kg'));
 const first=p.locator('.workout-set').first();await first.getByRole('checkbox').check();await first.getByLabel('Répétitions',{exact:true}).fill('11');await first.getByLabel('Charge (kg)',{exact:true}).fill('42.5');await p.getByLabel('Note de séance (facultatif)',{exact:true}).fill('Meilleure technique aujourd’hui.');await p.getByRole('button',{name:'Enregistrer cette séance',exact:true}).click();await p.getByRole('button',{name:'Commencer une nouvelle séance',exact:true}).waitFor();assert.equal((await p.evaluate(()=>window.performanceSaved)).notes,'Meilleure technique aujourd’hui.');await p.getByRole('button',{name:'Commencer une nouvelle séance',exact:true}).click();assert.match(await p.locator('.workout-set').first().innerText(),/11 répétitions · 42.5 kg/);assert.equal(await p.locator('.workout-set').first().getByLabel('Charge (kg)',{exact:true}).inputValue(),'');assert.equal(await p.locator('.workout-set').first().getByRole('checkbox').isChecked(),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'/private/tmp/aa-workout-references.png',fullPage:true});await p.close();
});
test('daily context note explains what may influence progress and is saved with the daily record',async()=>{
 const p=await trackingPage();await p.evaluate(async scripts=>{const m=await import(scripts+'/tracking.js');await m.mountTracking(document.querySelector('#client'),'fixture');},scripts);assert.match(await p.locator('.tracking-note-help').innerText(),/menstruations, insomnie, maladies, craquages, cheat meal/);await p.getByLabel('Notes',{exact:true}).fill('Insomnie et stress cette nuit.');await p.getByRole('button',{name:'Enregistrer mon suivi',exact:true}).click();await p.getByText('Suivi enregistré et partagé avec ton coach.').waitFor();assert.equal((await p.evaluate(()=>window.trackingCalls[0].p)).values_json.notes,'Insomnie et stress cette nuit.');await p.close();
});

function analysisStub(){return `const tables={coaching_analysis_settings:[{client_id:'fixture',revision:1,settings:{sleep_goal:8,steps_goal:8000,sites:{site1:{label:'Poitrine',enabled:true}},calculator:{age:30,weight:80,height:180}}}],daily_tracking_entries:[{recorded_on:'2026-10-05',metrics:{weight_kg:80,steps:7000,sleep_hours:7,calories:1900,protein_g:150,carbs_g:190,fat_g:60,notes:'Journée fictive'}},{recorded_on:'2026-10-04',metrics:{weight_kg:81,steps:0}}],coaching_roadmap:[],client_measurements:[],client_day_types:[],training_sessions:[],client_plan_versions:[]};window.analysisWrites=[];export const supabase={from(table){let write=null,filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},gte(){return q},order(){return q},range(){return q},limit(){return q},insert(v){write=v;return q},update(v){write=v;return q},upsert(v){write=v;return q},maybeSingle:async()=>({data:tables[table]?.[0]||null,error:null}),then(resolve){if(write){window.analysisWrites.push({table,value:write});const row={revision:1,...write};tables[table]=[row];return Promise.resolve({data:[row],error:null}).then(resolve);}return Promise.resolve({data:tables[table]||[],error:null}).then(resolve)}};return q}};`;}
async function analysisPage(){const p=await browser.newPage({viewport:{width:390,height:844}});await p.route('**/supabase.js*',r=>r.fulfill({status:200,contentType:'application/javascript',body:analysisStub()}));await p.goto(base+'/harness');await p.waitForFunction(()=>window.ready);return p;}
test('coach calculator applies only on explicit action, stores settings and dates the roadmap',async()=>{
 const p=await analysisPage();await p.evaluate(async()=>{window.analysis=await import(window.modules?'./'+(document.querySelector('script[type=module]').textContent.includes('/scripts/')?'scripts/':'')+'analysis.js':'');window.hub=await analysis.mountAnalysis(document.querySelector('#builder'),'fixture',{coach:true,applyTargets:(m,read)=>read?JSON.stringify({targets:{protein_g:150,carbs_g:200,fat_g:60}}):window.appliedMacros=m});});
 assert.equal(await p.evaluate(()=>window.appliedMacros),undefined);await p.getByRole('button',{name:'Appliquer au plan alimentaire en cours'}).click();assert.equal(await p.evaluate(()=>window.appliedMacros.protein_g),206.9);
 await p.getByRole('button',{name:'Enregistrer les paramètres du calculateur'}).click();await p.waitForFunction(()=>window.analysisWrites.length===1);assert.equal((await p.evaluate(()=>window.analysisWrites[0])).table,'coaching_analysis_settings');
 await p.getByText('Configurer une semaine de la roadmap',{exact:true}).click();await p.getByRole('button',{name:'Reprendre les macros du plan alimentaire'}).click();await p.getByRole('button',{name:'Enregistrer cette prescription datée'}).click();await p.waitForFunction(()=>window.analysisWrites.some(w=>w.table==='coaching_roadmap'));const saved=await p.evaluate(()=>window.analysisWrites.find(w=>w.table==='coaching_roadmap'));assert.equal(saved.value.prescription.rest.protein_g,150);assert.equal(new Date(saved.value.week_start).getUTCDay(),1);
 await p.getByText('Graphiques du suivi',{exact:true}).click();assert.ok(await p.locator('svg[role=img]').count()>=4);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.setViewportSize({width:1000,height:1200});await p.screenshot({path:root+'/review/analysis-charts.png',fullPage:false});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:root+'/review/analysis-coach.png',fullPage:false});await p.close();
});
test('client records enabled measurements and classifies a day for dated nutrition goals',async()=>{
 const p=await analysisPage();await p.evaluate(async()=>{const s=document.querySelector('script[type=module]').textContent.includes('/scripts/')?'scripts/':'';const a=await import('./'+s+'analysis.js');await a.mountAnalysis(document.querySelector('#builder'),'fixture');});
 await p.getByText('Mensurations',{exact:true}).click();await p.getByLabel('Poitrine (cm)').fill('100');await p.getByRole('button',{name:'Enregistrer mes mensurations'}).click();await p.waitForFunction(()=>window.analysisWrites.length===1);assert.equal((await p.evaluate(()=>window.analysisWrites[0])).value.measurements.site1,100);
 await p.getByLabel('Type de journée',{exact:true}).selectOption('training');await p.getByRole('button',{name:'Enregistrer le type de journée'}).click();await p.waitForFunction(()=>window.analysisWrites.some(w=>w.table==='client_day_types'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.close();
});
test('nutrition keeps independent day variants and client can choose a published day plan',async()=>{
 const p=await page();await p.evaluate(async()=>window.editor=await modules.nutrition.mountNutritionBuilder(document.querySelector('#nutrition')));await p.locator('#nutrition').getByLabel('Protéines (g)',{exact:true}).fill('150');await p.getByLabel('Version du plan alimentaire').selectOption('rest');await p.locator('#nutrition').getByLabel('Protéines (g)',{exact:true}).fill('100');const saved=await p.evaluate(()=>editor.serialize());const plan=JSON.parse(saved);assert.equal(plan.variants.standard.targets.protein_g,150);assert.equal(plan.variants.rest.targets.protein_g,100);await p.evaluate(value=>{document.querySelector('#nutrition').replaceChildren();modules.nutrition.renderClientNutrition(document.querySelector('#client'),value);},saved);await p.getByLabel('Type de plan alimentaire').selectOption('standard');assert.match(await p.locator('#client').innerText(),/150 g/);await p.close();
});
test('private photo comparison aligns the same pose across two dates',async()=>{
 const p=await browser.newPage({viewport:{width:390,height:844}});const sets=[{id:'new',photographed_on:'2026-10-05',paths:['new/front','new/side','new/back']},{id:'old',photographed_on:'2026-09-05',paths:['old/front','old/side','old/back']}];const stub=trackingStub().replace('rows=[],sets=[];',`rows=[],sets=${JSON.stringify(sets)};`);await p.route('**/supabase.js*',r=>r.fulfill({status:200,contentType:'application/javascript',body:stub}));await p.goto(base+'/harness');await p.waitForFunction(()=>window.ready);await p.evaluate(async()=>{const s=document.querySelector('script[type=module]').textContent.includes('/scripts/')?'scripts/':'';const photo=await import('./'+s+'progress-photos.js');await photo.mountPhotos(document.querySelector('#builder'),'fixture',{coach:true});});await p.locator('.photo-comparison img').first().waitFor();assert.equal(await p.locator('.photo-comparison img').count(),2);assert.match(await p.locator('.photo-comparison').innerText(),/2026-09-05/);await p.locator('select').filter({has:p.locator('option[value="2"]')}).selectOption('2');await p.waitForFunction(()=>document.querySelector('.photo-comparison img')?.alt.includes('Dos'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.close();
});
test('historical import requires CSV column preview and client confirmation before any RPC',async()=>{
 const p=await analysisPage();await p.evaluate(async()=>{const s=document.querySelector('script[type=module]').textContent.includes('/scripts/')?'scripts/':'';const a=await import('./'+s+'history-import.js');window.csv=a.parseCSV('\uFEFFdate;weight_kg;notes\n2026-10-04;80;"Contexte; fictif"');window.imports=[];const stub=await import('./'+s+'supabase.js?v=23');stub.supabase.rpc=async(name,p)=>{window.imports.push({name,p});return {data:[],error:null};};a.mountHistoryImport(document.querySelector('#builder'),'fixture');});assert.equal((await p.evaluate(()=>window.csv))[1][2],'Contexte; fictif');
 await p.locator('input[type=file]').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from('date,weight_kg,notes\n2026-10-04,80,Contexte fictif')});await p.getByRole('button',{name:'Préparer et vérifier l’aperçu'}).click();assert.equal(await p.getByRole('button',{name:'Importer les lignes vérifiées'}).isDisabled(),true);assert.equal(await p.evaluate(()=>window.imports.length),0);await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Importer les lignes vérifiées'}).click();await p.waitForFunction(()=>window.imports.length===1);assert.equal((await p.evaluate(()=>window.imports[0])).p.values_json.weight_kg,80);await p.close();
});
